### PR TITLE
Images side by side of height 140px

### PR DESCRIPTION
**Pull request by jasoncwy**
This is my pull request for the side by side images of height 140px

### CODE REVIEW

**Comment by SunyataZero** [comment]
Hi and thank you! I've looked at the result and it looks wonderful, a few things though:
* Can you change the images from the ones included in the application to screenshots of the application itself? This would mean that you have to add a few new files (maybe 3-5). The idea is to show the user what the application looks like
* Can you use markdown for showing the files instead of directly using html? There is a markdown syntax like this that you can use: `alt_text`

**Comment by srukle** [comment]
These images render well on my desktop. Question for @jasoncwy and @SunyataZero to consider, are these images licensed? And if so, must we publish a license document for them? Thanks!

**Comment by SunyataZero** [comment]
@srukle About the license: The images that @jasoncwy used are cc0, which means that they can be used without any attribution (i found them all using https://pixabay.com/ )

Yes the images are shown for me as well, but i'd like to show screenshots rather than the images for the "rest actions" in the application. Using markdown doesn't change anything in the presentation (i think) but it looks nicer :)

Kind Regards, Tord

**Comment by SunyataZero** [comment]
I've now closed this PR, but please feel free to open a new PR if you like. Kind Regards, Tord

**Pull request closed without merging**
