### PR TITLE
Included function type hints

### PR DESCRIPTION
**Pull request by j-nix**
Please let me know if you see any mistakes on my additions.

Many thanks
Joe

### CODE REVIEW

**Comment by SunyataZero** [comment]
@j-nix Thank you for working on this, it's nice to be able to cooperate like this!

The `db_conn` or database connection variable is of a type different than `str`, can you change the type hints to `https://docs.python.org/3.5/library/sqlite3.html#sqlite3.Connection` alternatively simply removing the type hints for them?

**Comment by j-nix** [comment]
Thanks for the feedback!

I've read the documentation and changed as you wish, I believe the type required to be int?

Let me know if not.
Thanks

**Comment by SunyataZero** [comment]
@j-nix I'm glad to help :) The version is an int yes but i think the database connection is of a special type which i haven't used before myself but which should be this i think: https://docs.python.org/3.5/library/sqlite3.html#sqlite3.Connection

Either you can simply remove the type hints for the db_conn variables or if you prefer you can try to use something like `i_db_conn: sqlite3.Connection`

Kind Regards, Tord

**Comment by j-nix** [comment]
Thanks for the direction!

Updated

**Comment by SunyataZero** [comment]
@j-nix Minor detail: Can you change the position of the space so that it's after the colon rather than before? (In other words `i_db_conn: sqlite3.Connection` rather than `i_db_conn :sqlite3.Connection`)
Because the TravisCI builds are broken (has nothing to do with your changes!) i don't know if this will have a real-world effect, so it's safest to put the space after
Kind Regards, Tord

**Comment by j-nix** [comment]
@SunyataZero No problem! I'll fix this in the morning.

Thanks

**Comment by SunyataZero** [comment]
@j-nix Merged, thank you!

**Comment by j-nix** [comment]
No problem, happy to help!

**Pull request merged**
