### PR TITLE
Issue #103 - Motivation

### PR DESCRIPTION
**Pull request by ap1459**
Added short paragraph on motivation, let me know what you think.

### CODE REVIEW

**Comment by SunyataZero** [comment]
@ap1459 Thank you for writing this, i think it looks wonderful, it's better than what i would have written and shows that we share an understanding of this idea (btw do you have experience with NVC or Nonviolent Communication? It looks like this from the text)

One thing i was thinking about was that we could maybe have a longer heading to make it clear that it's motivation for contributing, maybe something like "Motivation when working on this project", "Motivation when contributing to the project" or "Motivitation when contributing"?

Also i'm considering where to position this text paragraph, do we want it closer to the developer motivation section? Or even as a sub-section? I'm not sure

@mbed67 Marieke, do you have any thoughts on this?

**Comment by mbed67** [comment]
@ap1459 @SunyataZero This text is beautiful! I love it!
This text would fit well above the Developer Documentation I think. Also, I like "Motivation when contributing to this project"

**Comment by ap1459** [comment]
@SunyataZero @mbed67 I'm very pleased you like it! I can't say that I have any knowledge on the topic of NVC, but it is something I could look into in order to improve it or expand upon it. Having said that, if you believe it is sufficient as it is, that's also great!

I agree with you on the title change, I can change it to "Motivation when contributing to this project" if you would like.

**Comment by SunyataZero** [comment]
@ap1459 Yes to all questions :) Btw i think you are a natural NVC-practitioner!

**Comment by ap1459** [comment]
@SunyataZero Thank you very much! I shall go ahead and make the necessary changes.

**Comment by SunyataZero** [comment]
Merged!

**Pull request merged**
